### ISSUE TITLE
Argument of Type Optional[List[str]] doesn't work

### ISSUE THREAD

**Issue by AlJohri** [typed-argparse/typed-argparse#26]
Arguments with type `Optional[List[str]]` seem to be broken.

Program:

```python
#!/usr/bin/env python3

from typing import List, Optional
import typed_argparse as tap

class ExampleArgs(tap.TypedArgs):
    tags: Optional[List[str]] = tap.arg()

def runner(args: ExampleArgs):
    print(f"ARGS: {args}")

tap.Parser(ExampleArgs).bind(runner).run()
```

Invocation 1:

```shell
❯ python3 example.py       
ARGS: ExampleArgs(tags=None)
```

Invocation 2:

```shell
❯ python3 example.py --tags
usage: example.py [-h] [--tags TAGS]
example.py: error: argument --tags: expected one argument
```

Invocation 3:

```
python3 example.py --tags ""
Traceback (most recent call last):
  File "example.py", line 12, in <module>
    tap.Parser(ExampleArgs).bind(runner).run()
  File "/Users/aljohri/Development/typed-args-debug/.direnv/python-3.8.13/lib/python3.8/site-packages/typed_argparse/parser.py", line 221, in run
    typed_args = self._parser.parse_args(raw_args)
  File "/Users/aljohri/Development/typed-args-debug/.direnv/python-3.8.13/lib/python3.8/site-packages/typed_argparse/parser.py", line 167, in parse_args
    return arg_type.from_argparse(argparse_namespace)
  File "/Users/aljohri/Development/typed-args-debug/.direnv/python-3.8.13/lib/python3.8/site-packages/typed_argparse/typed_args.py", line 34, in from_argparse
    kwargs = _argparse_namespace_to_dict(cls, args, disallow_extra_args=disallow_extra_args)
  File "/Users/aljohri/Development/typed-args-debug/.direnv/python-3.8.13/lib/python3.8/site-packages/typed_argparse/typed_args.py", line 79, in _argparse_namespace_to_dict
    value = type_annotation.validate_with_error(value, arg_name)
  File "/Users/aljohri/Development/typed-args-debug/.direnv/python-3.8.13/lib/python3.8/site-packages/typed_argparse/type_utils.py", line 275, in validate_with_error
    raise TypeError(f"Failed to validate argument '{arg_name}': {error}")
TypeError: Failed to validate argument 'tags': value is of type 'str', expected 'list'
```

Invocation 4:

```
❯ python3 example.py --tags a
Traceback (most recent call last):
  File "example.py", line 12, in <module>
    tap.Parser(ExampleArgs).bind(runner).run()
  File "/Users/aljohri/Development/typed-args-debug/.direnv/python-3.8.13/lib/python3.8/site-packages/typed_argparse/parser.py", line 221, in run
    typed_args = self._parser.parse_args(raw_args)
  File "/Users/aljohri/Development/typed-args-debug/.direnv/python-3.8.13/lib/python3.8/site-packages/typed_argparse/parser.py", line 167, in parse_args
    return arg_type.from_argparse(argparse_namespace)
  File "/Users/aljohri/Development/typed-args-debug/.direnv/python-3.8.13/lib/python3.8/site-packages/typed_argparse/typed_args.py", line 34, in from_argparse
    kwargs = _argparse_namespace_to_dict(cls, args, disallow_extra_args=disallow_extra_args)
  File "/Users/aljohri/Development/typed-args-debug/.direnv/python-3.8.13/lib/python3.8/site-packages/typed_argparse/typed_args.py", line 79, in _argparse_namespace_to_dict
    value = type_annotation.validate_with_error(value, arg_name)
  File "/Users/aljohri/Development/typed-args-debug/.direnv/python-3.8.13/lib/python3.8/site-packages/typed_argparse/type_utils.py", line 275, in validate_with_error
    raise TypeError(f"Failed to validate argument '{arg_name}': {error}")
TypeError: Failed to validate argument 'tags': value is of type 'str', expected 'list'
```

**Comment by bluenote10** [comment]
Thanks for pointing that out! There are actually a couple of ways to handle that. If you're curious you may want to look into the test cases added in #28 if that is the behavior you'd expect.

**Comment by AlJohri** [comment]
Wow, thanks for the quick PR @bluenote10! And yep, the test cases (copied below) look very much in line with what I was expecting.

```python
args = parse(Args, [])
assert args.tags is None

args = parse(Args, ["--tags"])
assert args.tags == []

args = parse(Args, ["--tags", "a", "b", "c"])
assert args.tags == ["a", "b", "c"]
```

**Comment by bluenote10** [comment]
Thanks for verifying! Release should be on PyPI any second...
