### ISSUE TITLE
Feature Request: Handling Groups of Required Arguments?

### ISSUE THREAD

**Issue by AlJohri** [typed-argparse/typed-argparse#27]
I have a use case where I would like to have groups of arguments where either all of them are present or none of them are present. Essentially the flags are all related to each other and if any one of them is present, the rest of those related flags must also be present.

I have achieved this so far using the following code, but it is very verbose and doesn't read very nicely. The main reason is that it is relying on `__class__` to get the class members of the class in the current lexical scope.

Program:

```python
#!/usr/bin/env python3

from abc import ABC
from typing import Optional
import typed_argparse as tap


def get_class_member_names(cls):
    return [x for x in vars(cls) if not x.startswith("_") and not callable(getattr(cls, x))]


def filter_keys(d, keys):
    return {k: v for k, v in d.items() if k in keys}


class AllRequiredOrNone(tap.TypedArgs):
    def all_or_none_present(self, klass_name, members):
        d = filter_keys(self.__dict__, members)
        values = [x is not None for x in d.values()]
        if not (all(values) or not any(values)):
            keys_present = [k for k, v in d.items() if v is None]
            raise Exception(
                f"expected none or all members of {klass_name} to be present. "
                f"only {keys_present} were present out of expected {members}"
            )


class BaseArtifactSet(ABC, AllRequiredOrNone):
    def is_empty(self, members):
        d = filter_keys(vars(self), members)
        values = [x is not None for x in d.values()]
        return not any(values)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def as_dict(self):
        return {k: v for k, v in vars(self).items() if v is not None}


class GroupOneArtifactSet(BaseArtifactSet):
    group_one_param_one: Optional[str] = tap.arg()
    group_one_param_two: Optional[str] = tap.arg()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        members = get_class_member_names(__class__)
        self.all_or_none_present(__class__.__name__, members)

    def is_empty(self):
        members = get_class_member_names(__class__)
        return super().is_empty(members)

    def __repr__(self):
        kwargs_str = ", ".join([f"{k}={v}" for k, v in vars(self).items()])
        return f"{__class__.__name__}({kwargs_str})"


class GroupTwoArtifactSet(BaseArtifactSet):
    group_two_param_one: Optional[str] = tap.arg()
    group_two_param_two: Optional[str] = tap.arg()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        members = get_class_member_names(__class__)
        self.all_or_none_present(__class__.__name__, members)

    def is_empty(self):
        members = get_class_member_names(__class__)
        return super().is_empty(members)

    def __repr__(self):
        kwargs_str = ", ".join([f"{k}={v}" for k, v in vars(self).items()])
        return f"{__class__.__name__}({kwargs_str})"

class ExampleArgs(GroupTwoArtifactSet, GroupOneArtifactSet):
    my_global_arg: str = tap.arg()

def runner(args: ExampleArgs):
    print(f"ARGS: {args}")

tap.Parser(ExampleArgs).bind(runner).run()
```

Help Output:

```shell
❯ python example.py --help
usage: example.py [-h] [--group-one-param-one GROUP_ONE_PARAM_ONE] [--group-one-param-two GROUP_ONE_PARAM_TWO] [--group-two-param-one GROUP_TWO_PARAM_ONE] [--group-two-param-two GROUP_TWO_PARAM_TWO] --my-global-arg MY_GLOBAL_ARG

optional arguments:
  -h, --help            show this help message and exit
  --group-one-param-one GROUP_ONE_PARAM_ONE
  --group-one-param-two GROUP_ONE_PARAM_TWO
  --group-two-param-one GROUP_TWO_PARAM_ONE
  --group-two-param-two GROUP_TWO_PARAM_TWO
  --my-global-arg MY_GLOBAL_ARG
```

Invocation 1 (expected to work):

```shell
❯ python example.py --my-global-arg x --group-one-param-one x --group-one-param-two x
ARGS: GroupTwoArtifactSet(group_one_param_one=x, group_one_param_two=x, group_two_param_one=None, group_two_param_two=None, my_global_arg=x)
```

Invocation 2 (expected to work):

```shell
❯ python example.py --my-global-arg x --group-one-param-one x --group-one-param-two x --group-two-param-one x --group-two-param-two x
ARGS: GroupTwoArtifactSet(group_one_param_one=x, group_one_param_two=x, group_two_param_one=x, group_two_param_two=x, my_global_arg=x)
```

Invocation 3 (expected to fail):

```shell
❯ python example.py --my-global-arg x --group-one-param-one x --group-one-param-two x --group-two-param-one x                        
Traceback (most recent call last):
  File "example.py", line 82, in <module>
    tap.Parser(ExampleArgs).bind(runner).run()
  File "/Users/aljohri/Development/typed-args-debug/.direnv/python-3.8.13/lib/python3.8/site-packages/typed_argparse/parser.py", line 221, in run
    typed_args = self._parser.parse_args(raw_args)
  File "/Users/aljohri/Development/typed-args-debug/.direnv/python-3.8.13/lib/python3.8/site-packages/typed_argparse/parser.py", line 167, in parse_args
    return arg_type.from_argparse(argparse_namespace)
  File "/Users/aljohri/Development/typed-args-debug/.direnv/python-3.8.13/lib/python3.8/site-packages/typed_argparse/typed_args.py", line 35, in from_argparse
    return cls(**kwargs)
  File "example.py", line 66, in __init__
    self.all_or_none_present(__class__.__name__, members)
  File "example.py", line 22, in all_or_none_present
    raise Exception(
Exception: expected none or all members of GroupTwoArtifactSet to be present. only ['group_two_param_two'] were present out of expected ['group_two_param_one', 'group_two_param_two']
```

Invocation 4 (expected to fail):

```shell
❯ python example.py --my-global-arg x --group-one-param-one x --group-two-param-one x                        
Traceback (most recent call last):
  File "example.py", line 82, in <module>
    tap.Parser(ExampleArgs).bind(runner).run()
  File "/Users/aljohri/Development/typed-args-debug/.direnv/python-3.8.13/lib/python3.8/site-packages/typed_argparse/parser.py", line 221, in run
    typed_args = self._parser.parse_args(raw_args)
  File "/Users/aljohri/Development/typed-args-debug/.direnv/python-3.8.13/lib/python3.8/site-packages/typed_argparse/parser.py", line 167, in parse_args
    return arg_type.from_argparse(argparse_namespace)
  File "/Users/aljohri/Development/typed-args-debug/.direnv/python-3.8.13/lib/python3.8/site-packages/typed_argparse/typed_args.py", line 35, in from_argparse
    return cls(**kwargs)
  File "example.py", line 64, in __init__
    super().__init__(*args, **kwargs)
  File "example.py", line 48, in __init__
    self.all_or_none_present(__class__.__name__, members)
  File "example.py", line 22, in all_or_none_present
    raise Exception(
Exception: expected none or all members of GroupOneArtifactSet to be present. only ['group_one_param_two'] were present out of expected ['group_one_param_one', 'group_one_param_two']
```

Invocation 5 (expected to work):

```shell
❯ python example.py --my-global-arg x                                                
ARGS: GroupTwoArtifactSet(group_one_param_one=None, group_one_param_two=None, group_two_param_one=None, group_two_param_two=None, my_global_arg=x)
```

Any easier ways to do this? Perhaps a pattern that could be supported by the library itself?

**Comment by bluenote10** [comment]
Yeah that is definitely a sensible thing to add. Some thoughts:

I would have to look into what argparse itself offers here, because it has [argument groups](https://docs.python.org/3/library/argparse.html#argument-groups). So one possibility would be to leverage that.

Another idea: What do think about offering a argument validation hook?

```python
class GroupOneArtifactSet(BaseArtifactSet):
    group_one_param_one: Optional[str] = tap.arg()
    group_one_param_two: Optional[str] = tap.arg()

    def __validate__(self):
       params = [self.group_one_param_one is None, self.group_one_param_two is None]
       num_defined = sum(1 if param is None else 0 for param in params)
       if num_defined != 0 or num_defined != len(params):
           raise ArgumentError("expected none or all members to be defined")
```

A benefit of that solution that it would allow for arbitrarily complex arg validation hooks. A downside would be that it is not (easily) possible to automatically communicate in the help text that the two arguments are coupled.

What do you think?

**Comment by AlJohri** [comment]
Argument Groups would be really nice to to leverage for a better `--help` output, but unfortunately that won't do much to achieve this "all or nothing" kind of functionality. This feature was requested in the python bug tracker (https://bugs.python.org/issue11588) quite a long time ago under the name "necessarily inclusive" group or "mutually dependent" group but was never accepted, so its likely argparse won't be able to directly help here.

I think `__validate__` might be helpful in the general sense, _but_ I really like this library (over regular argparse) because it allows me to use the type system and classes to declaratively describe what the CLI should look like.

Where possible, I think it would be great to continue to add more functionality that can be described declaratively such that it can both automatically perform this check and automatically represent it in the help text, etc.

Although I also completely understand that this library is built on top of argparse and this is functionality is squarely outside of argparse so perhaps exposing an escape hatch like `__validate__` is the best one can do.

**Comment by bluenote10** [comment]
Yeah I think I need to give it a bit more thought before jumping to a conclusion. From a user perspective perhaps something like this would be nice:

```python
class GroupOneArtifactSet(ArgumentGroup, enable_all_or_none=True):
    group_one_param_one: Optional[str] = tap.arg()
    group_one_param_two: Optional[str] = tap.arg()
```

Deriving from `ArgumentGroup` itself could make the arguments appear as a group in the help text, and the `enable_all_or_none` could allow to opt-in to the validation step that makes sure that either all or none arguments are given.

A perfect solution would require to express the "all or nothing" even in the type system. The issue with the individual `Optional` is that they fail to express that if one is defined the others must be defined as well. Seems tricky to achieve, but I haven't thought about it enough to rule out it out entirely. Perhaps something like:

```python
class MyArgumentGroupA(ArgumentGroup):
    param_one: str = tap.arg()
    param_two: str = tap.arg()

class MyArgumentGroupB(ArgumentGroup):
    foo: str = tap.arg()
    bar: str = tap.arg()

class Args(TypedArgs):
    group_one: Optional[MyArgumentGroupA] = tap.arg()
    group_two: Optional[MyArgumentGroupB] = tap.arg()
```

But I would have to check if diverging from the current "all arguments are flat" design could cause issue (because internally that's not how `argparse.Namespace` works).

**Comment by AlJohri** [comment]
one edge case I found with my implementation is that if a group has an argument with a default value, than it raises an exception because it sees only one value out of the group having a non-null value, so the "all or none" condition gets triggered
