### ISSUE TITLE
Detecting conflicts between common args and sub command args

### ISSUE THREAD

**Issue by bluenote10** [typed-argparse/typed-argparse#55]
The following code demonstrate a possible pitfalls with conflicting type information between the `common_args` of a parser group and the particular arguments of one of its sub-parsers:

```py
import typed_argparse as tap


class CommonArgs(tap.TypedArgs):
    some_arg: str


class SubCommandArgs(tap.TypedArgs):
    some_arg: int


def run_sub_command(args: SubCommandArgs) -> None:
    print(f"Running sub command: {args}")


def main() -> None:
    tap.Parser(
        tap.SubParserGroup(
            tap.SubParser(
                "sub-command",
                SubCommandArgs,
            ),
            common_args=CommonArgs,
        ),
    ).bind(
        run_sub_command,
    ).run()


if __name__ == "__main__":
    main()
```

Here neither the type system nor a runtime check (while constructing the parser) detects that issue that `some_arg` must not be overriden by a sub-command, because argparse will already add it to the parent parser group. The issue will only show up when a user tries to execute this particular sub-command:

```sh
$ python test.py --some-arg 42 sub-command

Traceback (most recent call last):
  File "/tmp/test.py", line 31, in <module>
    main()
  File "/tmp/test.py", line 27, in main
    ).run()
  File "/home/fabian/.virtualenvs/default3/lib/python3.10/site-packages/typed_argparse/parser.py", line 248, in run
    typed_args = self._parser.parse_args(raw_args)
  File "/home/fabian/.virtualenvs/default3/lib/python3.10/site-packages/typed_argparse/parser.py", line 194, in parse_args
    return arg_type.from_argparse(argparse_namespace)
  File "/home/fabian/.virtualenvs/default3/lib/python3.10/site-packages/typed_argparse/typed_args.py", line 34, in from_argparse
    kwargs = _argparse_namespace_to_dict(cls, args, disallow_extra_args=disallow_extra_args)
  File "/home/fabian/.virtualenvs/default3/lib/python3.10/site-packages/typed_argparse/typed_args.py", line 79, in _argparse_namespace_to_dict
    value = type_annotation.validate_with_error(value, arg_name)
  File "/home/fabian/.virtualenvs/default3/lib/python3.10/site-packages/typed_argparse/type_utils.py", line 278, in validate_with_error
    raise TypeError(f"Failed to validate argument '{arg_name}': {error}")
TypeError: Failed to validate argument 'some_arg': value is of type 'str', expected 'int'
```

I'm not sure if the issue could be detected at type checking time, but even a runtime _during_ the construction of the parser would allow to detect the issue much more reliably/earlier, because any unit test (or manual `my_app --help`) would detect that there is an issue, and a much clearer error message could be generated: 

_The sub-command parser SubParser tries to define an argument called '--some-arg' of type int, but there is already a parent parser CommonArgs that defines the same argument of type str._

**Comment by bluenote10** [comment]
Yes indeed, the best way to prevent any issue on user side is to use inheritance. Currently there is just no mechanism that forces the user to use inheritance, which has some potential to shoot oneself in the foot.

To make it less error prone I plan to implement:
- a runtime check, which would check that no subparser adds a conflicting argument. That could also be helpful when using lots of argument aliases (some `--custom-arg-name` which deviates from the name in the type system), which could also conflict. I think its possible to perform the check already when building the parser, i.e., even before any actual parsing. If a user has a unit test for building the parser this would already guarantee that the CLI is conflict free (i.e., no need to write lots of unit tests to test each and every subparser).
- check it via the type system. This would mean that inheritance becomes more or less enforced. I'd need to look into whether it is actually possible. Perhaps `SubParser` and `SubParserGroup` need to become generic in the common base type to express the relationship.
